# Generated by Django 5.2 on 2025-04-26 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="accuracy",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="behavioral_interviews",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="coherence",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="fluency",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="grammar",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="overall_rating",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="technical_interviews",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="total_interviews",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="year_of_joining",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="college_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="InterviewAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[("Technical", "Technical"), ("HR", "HR")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("fluency", models.IntegerField()),
                ("content_structure", models.IntegerField()),
                ("accuracy", models.IntegerField()),
                ("grammar", models.IntegerField()),
                ("vocabulary", models.IntegerField()),
                ("coherence", models.IntegerField()),
                ("overall_rating", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
