# Generated by Django 5.2 on 2025-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_customuser_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="year_of_joining",
            field=models.IntegerField(default=0),
        ),
    ]
