# Generated by Django 5.2 on 2025-06-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewattempt",
            name="interview_type",
            field=models.CharField(
                choices=[("Technical", "Technical"), ("HR", "HR")], max_length=100
            ),
        ),
    ]
